(defun physics (ent)
  ;(setf (x dot) (+ (x dot) (* (x_v dot) (sdl:dt))))
  ;(setf (y dot) (+ (y dot) (* (y_v dot) (sdl:dt)))))
  (if (OR (AND (< (x_v ent) 50) 
	       (> (x_v ent) 0))
	  (AND (> (x_v ent) 50) 
	       (< (x_v ent) 0)))
      (setf (x_v ent) 
	    (+ (x_v ent) 
	       (* (elt (a ent) 0) 
		  (sdl:dt))))
      (setf (elt (a ent) 0) 
	    0))
  (setf (y_v ent) 
	(+ (y_v ent) 
	   (* (elt (a ent) 1) 
	      (sdl:dt))))
  (setf (x ent) 
	(+ (x ent) 
	   (* (x_v ent) 
	      (sdl:dt)) 
	   (* 1/2 
	      (elt (a ent) 0) 
	      (expt (sdl:dt) 
		    2))))
  (setf (y ent) 
	(+ (y ent) 
	   (* (y_v ent) 
	      (sdl:dt))
	   (* 1/2 
	      (elt (a ent) 1) 
	      (expt (sdl:dt) 
		    2))))
  ;(addVector (* 0.001 (x_v ent)) (* 0.001 (y_v ent)))

      (unless (OR (keyDown :sdl-key-j)
		  (keyDown :sdl-key-l))
	(if (> (abs (x_v ent)) 0.1)
	    (setf (x_v ent) (* 0.75 (x_v ent)))
	    (setf (x_v ent) 0)))

      (unless (OR (keyDown :sdl-key-k)
		  (keyDown :sdl-key-i))
	(if (> (abs (y_v ent)) 0.1)
	    (setf (y_v ent) (* 0.75 (y_v ent)))
	    (setf (y_v ent) 0)))
  
  (setf (elt (pos ent) 0) (x ent))
  (setf (elt (pos ent) 1) (y ent)))
